import { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Service = { id: string; name: string; description: string; price: number };
type Payment = { id: string; service: string; amount: number; status: 'confirmed' | 'demo'; signature: string | null; createdAt: string };
type Activity = { label: string; detail?: string; tone: 'info' | 'payment' | 'success' | 'error'; signature?: string | null };
type Run = { activities: Activity[]; payments: Payment[]; spent: number; remaining: number; result: { supplier: string; cost: number; verification: string; esg: number; renewable: number } };
type View = 'overview' | 'run' | 'services' | 'payments' | 'policies';

const DEFAULT_PROMPT = 'Find the best Malaysian solar supplier under RM50,000 and evaluate its ESG profile.';
const BUDGET = 0.05;
const TIMING = { firstEvent: 0, eventStep: 155 };
const LABELS: Record<string, string> = { 'supplier-search': 'Supplier Intelligence', 'company-verification': 'Company Verification', esg: 'ESG Intelligence' };
const REASONS: Record<string, string> = {
  'supplier-search': "The agent needed supplier intelligence to compare candidates against the user's RM50,000 budget.",
  'company-verification': 'The agent needed company verification before recommending a supplier.',
  esg: 'The agent needed an ESG profile to evaluate the supplier beyond price and rating.'
};

/* ─────────────────────────────────────────────────────────
 * DEMO STORYBOARD
 *   0ms  user can start the run immediately
 * 155ms  next operational event appears in the trace
 * Reduced motion reveals the completed operational trace instantly.
 * ───────────────────────────────────────────────────────── */

function App() {
  const [prompt, setPrompt] = useState(DEFAULT_PROMPT), [services, setServices] = useState<Service[]>([]), [demo, setDemo] = useState(true);
  const [run, setRun] = useState<Run | null>(null), [ledger, setLedger] = useState<Payment[]>([]), [loading, setLoading] = useState(false), [visibleEvents, setVisibleEvents] = useState(0);
  const [apiStatus, setApiStatus] = useState<'loading' | 'ready' | 'error'>('loading'), [error, setError] = useState(''), [view, setView] = useState<View>('overview'), [paused, setPaused] = useState(false);
  async function loadConfig() { setApiStatus('loading'); try { const response = await fetch('/api/config'); if (!response.ok) throw new Error(); const config = await response.json(); setServices(config.services); setDemo(config.demoMode); setApiStatus('ready'); setError(''); return true; } catch { setApiStatus('error'); setError('The AgentPay API is unavailable. Start the local app, then try the connection again.'); return false; } }
  useEffect(() => { void loadConfig(); }, []);
  useEffect(() => { if (!run) return; if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) { setVisibleEvents(run.activities.length); return; } setVisibleEvents(0); const timers = run.activities.map((_, index) => window.setTimeout(() => setVisibleEvents(index + 1), TIMING.firstEvent + index * TIMING.eventStep)); return () => timers.forEach(window.clearTimeout); }, [run]);
  const payments = useMemo(() => run?.payments || ledger, [run, ledger]); const spent = run?.spent || payments.reduce((sum, payment) => sum + payment.amount, 0); const remaining = Math.max(0, BUDGET - spent); const percent = Math.min(100, spent / BUDGET * 100);
  async function start() { if (paused) { setError('The demo session is paused. Resume the agent before starting a new run.'); return; } if (apiStatus !== 'ready' && !(await loadConfig())) return; setLoading(true); setError(''); setRun(null); setVisibleEvents(0); setView('run'); try { const response = await fetch('/api/agent/run', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ prompt }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Agent run failed.'); setRun(data); setLedger(data.payments); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Agent run failed.'); } finally { setLoading(false); } }
  const nav: { id: View; label: string }[] = [{ id: 'overview', label: 'Overview' }, { id: 'run', label: 'Agent Run' }, { id: 'services', label: 'Services' }, { id: 'payments', label: 'Payments' }, { id: 'policies', label: 'Policies' }];
  return <div className="app-shell"><header className="topbar"><button className="brand" onClick={() => setView('overview')} aria-label="AgentPay overview"><span className="brand-mark" aria-hidden="true">A</span><span><strong>AGENTPAY</strong><small>Financial control layer for AI agents</small></span></button><nav aria-label="Primary navigation">{nav.map(item => <button key={item.id} className={`nav-item ${view === item.id ? 'active' : ''}`} aria-current={view === item.id ? 'page' : undefined} onClick={() => setView(item.id)}>{item.label}</button>)}</nav><div className="network-status"><span className="status-dot" aria-hidden="true"/>Solana Devnet{demo && <span className="demo-label">SIMULATED DATA</span>}</div></header><main>
    {view === 'overview' && <Overview services={services} run={run} spent={spent} remaining={remaining} percent={percent} paused={paused} loading={loading} start={start} setView={setView}/>} {view === 'run' && <AgentRun prompt={prompt} setPrompt={setPrompt} run={run} loading={loading} visibleEvents={visibleEvents} error={error} start={start} apiStatus={apiStatus} retry={loadConfig}/>} {view === 'services' && <Services services={services} runDemo={start} loading={loading}/>} {view === 'payments' && <Payments payments={payments} demo={demo}/>} {view === 'policies' && <Policies paused={paused} setPaused={setPaused}/>}</main></div>;
}

function Overview({ services, run, spent, remaining, percent, paused, loading, start, setView }: { services: Service[]; run: Run | null; spent: number; remaining: number; percent: number; paused: boolean; loading: boolean; start: () => Promise<void>; setView: (v: View) => void }) { return <><section className="hero"><div><p className="kicker">CONTROL · CONTEXT · PROOF</p><h1>Your AI can work.<br/><span>Now let it pay.</span></h1><p className="hero-copy">Give AI agents a controlled budget to purchase the digital services they need — automatically, transparently, and on Solana.</p><div className="hero-actions"><button className="button primary" onClick={() => void start()} disabled={loading || paused}>{loading ? 'RUNNING LIVE DEMO…' : 'RUN LIVE DEMO'} <b aria-hidden="true">→</b></button><button className="button secondary" onClick={() => setView('services')}>EXPLORE SERVICES</button></div>{paused && <p className="inline-warning" role="status">Demo session is paused. Resume it in Policies to run the agent.</p>}</div><div className="hero-proof"><p className="kicker">THE PAYMENT LOOP</p><div className="loop">REQUEST <i>→</i> 402 <i>→</i> POLICY <i>→</i> PAY <i>→</i> PROOF</div><p>Every paid request is policy-checked before it can unlock a service.</p></div></section><section className="dashboard-grid"><BudgetCard spent={spent} remaining={remaining} percent={percent} count={run?.payments.length || 0}/><PolicySummary paused={paused} onView={() => setView('policies')}/><section className="card last-run"><div className="card-heading"><div><p className="kicker">LAST AGENT RUN</p><h2>{run ? 'Completed with guardrails' : 'Ready for a controlled run'}</h2></div><button className="text-button" onClick={() => setView('run')}>Open trace →</button></div><p>{run ? 'Three paid capabilities were requested, policy-checked, and released to the agent.' : 'Start the demo to see every request, payment decision, and receipt.'}</p><div className="mini-steps"><span>REQUEST</span><span>POLICY</span><span>PAYMENT</span><span>RESULT</span></div></section></section><section className="section-block"><div className="section-heading"><div><p className="kicker">AVAILABLE SERVICES</p><h2>Services your agent can buy</h2><p>No subscriptions. Pay only when your agent needs it.</p></div><button className="text-button" onClick={() => setView('services')}>View catalogue →</button></div><ServiceGrid services={services} compact/></section></>; }
function BudgetCard({ spent, remaining, percent, count }: { spent: number; remaining: number; percent: number; count: number }) { return <section className="card budget-card"><p className="kicker">AGENT BUDGET</p><div className="budget-value">$0.050 <small>USDC</small></div><div className="progress" aria-label={`${percent.toFixed(0)}% of session budget spent`}><span style={{ width: `${percent}%` }}/></div><dl className="budget-stats"><Metric label="Spent" value={`$${spent.toFixed(3)}`}/><Metric label="Remaining" value={`$${remaining.toFixed(3)}`}/><Metric label="Transactions" value={String(count)}/><Metric label="Interventions" value="0"/></dl><p className="network-note"><span aria-hidden="true">●</span> Solana Devnet</p></section>; }
function PolicySummary({ paused, onView }: { paused: boolean; onView: () => void }) { return <section className="card policy-card"><div className="card-heading"><div><p className="kicker">AGENT POLICY</p><h2>{paused ? 'Paused' : 'Active'}</h2></div><span className={`state ${paused ? 'paused' : 'active-state'}`}>{paused ? 'PAUSED' : 'ACTIVE'}</span></div><dl className="policy-list"><Metric label="Maximum per transaction" value="$0.010"/><Metric label="Session budget" value="$0.050"/><Metric label="Allowed services" value="3"/><Metric label="Auto-approve" value="ON"/></dl><button className="text-button policy-link" onClick={onView}>Review policy →</button></section>; }
function AgentRun({ prompt, setPrompt, run, loading, visibleEvents, error, start, apiStatus, retry }: { prompt: string; setPrompt: (v: string) => void; run: Run | null; loading: boolean; visibleEvents: number; error: string; start: () => Promise<void>; apiStatus: 'loading' | 'ready' | 'error'; retry: () => Promise<boolean> }) { const payment = run?.payments[Math.min(run.payments.length - 1, Math.floor(visibleEvents / 7))]; return <><section className="page-heading"><p className="kicker">AGENT RUN</p><h1>Operational trace, not black-box thinking.</h1><p>See the request, policy decision, payment outcome, and service result.</p></section><div className="run-layout"><section className="card task-card"><div className="card-heading"><div><p className="kicker">TASK</p><h2>What should the agent do?</h2></div><span className="state active-state">GUARDED</span></div><label htmlFor="agent-task">Agent task</label><textarea id="agent-task" value={prompt} onChange={event => setPrompt(event.target.value)}/><p className="field-note">The session cap is $0.050 USDC. Requests at or below $0.010 are eligible for auto-approval.</p><button className="button primary full" onClick={() => void start()} disabled={loading || apiStatus === 'loading'} aria-busy={loading}>{loading ? 'RUNNING AGENT…' : apiStatus === 'loading' ? 'CONNECTING…' : 'RUN LIVE DEMO'} <b aria-hidden="true">→</b></button>{error && <div className="error-box" role="alert"><strong>Action needed</strong><span>{error}</span>{apiStatus === 'error' && <button onClick={() => void retry()} className="text-button">Retry connection →</button>}</div>}</section><section className="card decision-card"><p className="kicker">AGENT DECISION</p><h2>{payment ? `“${REASONS[payment.service]}”` : '“I will buy only the capabilities needed to answer the task.”'}</h2><dl className="decision-list"><Metric label="Service" value={payment ? LABELS[payment.service] : 'Supplier Intelligence'}/><Metric label="Cost" value={payment ? `$${payment.amount.toFixed(3)} USDC` : '$0.002 USDC'}/><Metric label="Remaining budget" value={run ? `$${run.remaining.toFixed(3)}` : '$0.050'}/><Metric label="Policy" value="✓ Within limit"/></dl><div className="auto-approval">AUTO APPROVE <span>≤ $0.010</span></div></section></div><section className="card timeline-card"><div className="card-heading"><div><p className="kicker">AGENT ACTIVITY</p><h2>{loading ? 'Executing live workflow' : run ? 'Completed workflow' : 'Waiting for a task'}</h2></div>{loading && <span className="live"><i/> LIVE</span>}</div>{!run && !loading && <Empty/>}{run && <div className="timeline">{run.activities.slice(0, visibleEvents).map((activity, index) => <ActivityItem activity={activity} key={`${activity.label}-${index}`}/>)}</div>}</section>{run && <><WhySpend payments={run.payments}/><Receipt run={run}/><Result result={run.result}/></>}</>; }
function ActivityItem({ activity }: { activity: Activity }) { return <article className={`event ${activity.tone}`}><span className="event-dot" aria-hidden="true"/><div><strong>{activity.label}</strong>{activity.detail && <p>{activity.signature ? <a href={`https://explorer.solana.com/tx/${activity.signature}?cluster=devnet`} target="_blank" rel="noreferrer">{short(activity.detail)} ↗</a> : activity.detail}</p>}{activity.label === '402 PAYMENT REQUIRED' && <span className="event-meta">Price disclosed by service</span>}{activity.label === 'BUDGET CHECK' && <span className="event-meta">Policy allows this service and amount</span>}</div></article>; }
function Empty() { return <div className="empty-state"><strong>No activity yet</strong><p>Run the demo to reveal the operational trace one step at a time.</p></div>; }
function WhySpend({ payments }: { payments: Payment[] }) { return <section className="section-block"><div className="section-heading"><div><p className="kicker">PAYMENT CONTEXT</p><h2>Why did the agent spend?</h2><p>Every payment is tied to the decision that made it necessary.</p></div></div><div className="why-grid">{payments.map(payment => <article className="card why-card" key={payment.id}><p className="kicker">WHY THIS PAYMENT?</p><h3>{REASONS[payment.service]}</h3><dl><Metric label="Service" value={LABELS[payment.service]}/><Metric label="Cost" value={`$${payment.amount.toFixed(3)} USDC`}/><Metric label="Policy" value="Auto-approved"/><Metric label="Result" value="Service data received"/></dl><p className="settled">✓ {payment.signature ? 'SETTLED ON SOLANA' : 'DEMO RECEIPT VERIFIED'}</p></article>)}</div></section>; }
function Receipt({ run }: { run: Run }) { return <section className="receipt"><div><p className="kicker">AGENT RECEIPT</p><h2>Research Malaysian solar suppliers</h2><p>Completed with transparent spend context and verified access receipts.</p></div><dl><Metric label="Services purchased" value="3"/><Metric label="Total" value={`$${run.spent.toFixed(3)} USDC`}/><Metric label="Human interventions" value="0"/><Metric label="Budget remaining" value={`$${run.remaining.toFixed(3)} USDC`}/><Metric label="Solana transactions" value={String(run.payments.filter(payment => payment.signature).length)}/></dl></section>; }
function Result({ result }: { result: Run['result'] }) { return <section className="card result-card"><p className="kicker">SIMULATED DATA · DEVNET DEMO</p><h2>Recommended supplier</h2><h3>{result.supplier}</h3><dl className="result-grid"><Metric label="Estimated project cost" value={`RM${result.cost.toLocaleString()}`}/><Metric label="Verification" value="SIMULATED / DEMO"/><Metric label="ESG score" value={`${result.esg}/100`}/><Metric label="Renewable mix" value={`${result.renewable}%`}/></dl></section>; }
function Services({ services, runDemo, loading }: { services: Service[]; runDemo: () => Promise<void>; loading: boolean }) { return <><section className="page-heading"><p className="kicker">MARKETPLACE</p><h1>Services your agent can buy</h1><p>No subscriptions. Pay only when your agent needs it.</p></section><ServiceGrid services={services} action={() => void runDemo()} loading={loading}/></>; }
function ServiceGrid({ services, compact = false, action, loading }: { services: Service[]; compact?: boolean; action?: () => void; loading?: boolean }) { return <div className={`service-grid ${compact ? 'compact' : ''}`}>{services.length ? services.map(service => <article className="card service-card" key={service.id}><p className="kicker">x402 · USDC · SOLANA</p><h3>{service.name}</h3><p>{service.description}</p><div className="service-price">${service.price.toFixed(3)} <small>/ request</small></div>{!compact && <button className="button secondary full" onClick={action} disabled={loading}>{loading ? 'RUNNING…' : 'USE SERVICE'}</button>}</article>) : <div className="card loading-cards" aria-live="polite">Loading available services…</div>}</div>; }
function Payments({ payments, demo }: { payments: Payment[]; demo: boolean }) { return <><section className="page-heading"><p className="kicker">PAYMENTS</p><h1>Contextual payment ledger</h1><p>Every line answers what was bought, why it was needed, and whether a verifiable transaction exists.</p></section><section className="card ledger-card">{payments.length ? <div className="table-wrap"><table><thead><tr><th>Time</th><th>Service</th><th>Why</th><th>Amount</th><th>Status</th><th>Transaction</th></tr></thead><tbody>{payments.map(payment => <tr key={payment.id}><td>{new Date(payment.createdAt).toLocaleTimeString()}</td><td>{LABELS[payment.service]}</td><td>{REASONS[payment.service]}</td><td>${payment.amount.toFixed(3)}</td><td><span className={payment.status === 'confirmed' ? 'state active-state' : 'state'}>{payment.status === 'confirmed' ? 'SETTLED' : 'DEMO RECEIPT'}</span></td><td>{payment.signature ? <a href={`https://explorer.solana.com/tx/${payment.signature}?cluster=devnet`} target="_blank" rel="noreferrer">View on Explorer ↗</a> : <span className="muted">No on-chain transaction in Demo Mode</span>}</td></tr>)}</tbody></table></div> : <div className="empty-state"><strong>No payments yet</strong><p>{demo ? 'Run the live demo to create local demo receipts. Real signatures appear only when real settlement is configured.' : 'Complete a run to see your transaction ledger.'}</p></div>}</section></>; }
function Policies({ paused, setPaused }: { paused: boolean; setPaused: (v: boolean) => void }) { return <><section className="page-heading"><p className="kicker">POLICIES</p><h1>Autonomous, but constrained.</h1><p>These controls define the demo session policy before an agent authorizes a paid request.</p></section><section className="policy-layout"><section className="card policy-form"><div className="card-heading"><div><p className="kicker">ACTIVE POLICY</p><h2>Demo session controls</h2></div><span className={`state ${paused ? 'paused' : 'active-state'}`}>{paused ? 'PAUSED' : 'ACTIVE'}</span></div><dl className="policy-list detailed"><Metric label="Session budget" value="$0.050 USDC"/><Metric label="Maximum per transaction" value="$0.010 USDC"/><Metric label="Auto-approval threshold" value="$0.010 USDC"/><Metric label="Allowed services" value="Supplier Intelligence · Company Verification · ESG Intelligence"/></dl><div className="control-row"><button className="button secondary" onClick={() => setPaused(!paused)}>{paused ? 'RESUME AGENT' : 'PAUSE AGENT'}</button><button className="button danger" onClick={() => setPaused(true)}>STOP SPENDING</button></div><p className="field-note">These controls pause new demo runs in this browser. Server-side budget enforcement remains part of the x402 run flow.</p></section><aside className="card control-note"><p className="kicker">CONTROL BOUNDARY</p><h2>What the agent cannot do</h2><ul><li>Spend above the $0.050 session budget</li><li>Purchase outside the three allowed capabilities</li><li>Auto-approve a request over $0.010</li></ul></aside></section></>; }
function Metric({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
function short(value: string) { return `${value.slice(0, 5)}…${value.slice(-4)}`; }
createRoot(document.getElementById('root')!).render(<App />);
